### ISSUE TITLE
Does Not work in Overleaf Does it require loading the font as a custom font into the doc?

### ISSUE THREAD

**Issue by moaraj** [diogo-fernan/academicons#10]

**Comment by moaraj** [comment]
A small note in the documentation that says put the .ttf in the same folder as the tex file you're trying to compile the following in your header, 
`\newfontfamily{\AI}{Academicons}`
or installing the font on your PC would fix the issue for those who don't use overleaf

**Comment by diogo-fernan** [comment]
Hi there. Please me more descriptive and less confusing in your comment. I am unsure of what you mean.

The documentation clearly states that the `*.ttf` font file has to be installed on the system.
