### ISSUE TITLE
\newfontfamily{\AI}{academicons.ttf} causes font not to be loaded on Windows 10

### ISSUE THREAD

**Issue by jessequinn** [diogo-fernan/academicons#3]
I suggest using \newfontfamily{\AI}{Academicons} and physically installing the font for windows 10. The other route the font isn't loaded.

**Comment by diogo-fernan** [comment]
Updated in https://github.com/diogo-fernan/academicons/commit/6783fe8892668bf3d2dbf63891c99a58938644c5.
