### ISSUE TITLE
Update to 1.8.6 icons

### ISSUE THREAD

**Issue by jessequinn** [diogo-fernan/academicons#4]
Hi Diogo,

Can you please update to 1.8.6 icons?

Thanks

**Comment by diogo-fernan** [comment]
Updated in https://github.com/diogo-fernan/academicons/commit/6783fe8892668bf3d2dbf63891c99a58938644c5.

**Comment by jessequinn** [comment]
updated on latex servers for MikTek and others?

**Comment by diogo-fernan** [comment]
LaTeX (and derivatives) packages are maintained by CTAN, to where academicons was updated at https://www.ctan.org/pkg/academicons.
