### ISSUE TITLE
Using academicons in the ShareLatex plataform

### ISSUE THREAD

**Issue by adrianohrl** [diogo-fernan/academicons#5]
Given that this package has special system settings for being used, have you already contacted to the ShareLaTeX support team in order to properly set this package in their system? If so, what should I do to use this package in ShareLaTeX properly?

**Comment by diogo-fernan** [comment]
The *academicons* requires the Academicons font to be installed on the system where the package is installed. Therefore, the ShareLaTeX platform would have to install the font in addition to the package.

**Comment by adrianohrl** [comment]
I have found an easy way to use this package in the ShareLaTeX platform. It is described below.

Firstly, it is necessary to upload the [academicons.sty](https://raw.githubusercontent.com/diogo-fernan/academicons/722cba257291bcde83b44cf8af0cd8993597d6bd/academicons.sty?raw=true) and [academicons.ttf](https://github.com/diogo-fernan/academicons/blob/722cba257291bcde83b44cf8af0cd8993597d6bd/academicons.ttf?raw=true) files to the desired ShareLaTeX project.

Afterwards, in case the academicons.sty file content have the following command

`\newfontfamily{\AI}{Academicons}`

change it to:

`\newfontfamily{\AI}{academicons.ttf}`

Try the following inputs to your main.tex document in order to test this LaTeX package setup:

`\usepackage{academicons}`

and inside its "document" environtment, enter:

`\aiicons{lattes}`

Finally, check if the following icon:

 ![Lattes Logo](https://raw.githubusercontent.com/adrianohrl/adrianohrl.github.io/master/assets/logos/lattes/64x64.png?raw=true)

If so, you are all set!
