### ISSUE TITLE
\aiIdeasRepec issue....

### ISSUE THREAD

**Issue by JeffreyRacine** [diogo-fernan/academicons#8]
Greetings Diogo,

\aiicon{ideas-repec} generates the correct icon, but your documentation indicates that \aiIdeasRepec ought to generate the same, but it does not. Trial and error indicates that \aiIDEASRePEc almost works but it produces \aiicon{ideas-repec-square}.

Furthermore calling aiicon{} versus Direct Command have different behaviour and Direct Command is better behaved for me... for instance

    [\aiicon{ideas-repec}IDEAS/RePEc:](https://ideas.repec.org/e/pra175.html)

kills the label IDEAS/RePEc while

    [\aiIDEASRePEc\ IDEAS/RePEc:](https://ideas.repec.org/e/pra175.html)

leaves it intact.

If by chance you might have time to correct the \aiIdeasRepec to point to \ai{ideas-repec} per your documentation that would be most appreciated. 

Thanks again!

**Comment by diogo-fernan** [comment]
Hi Jeffrey,

Thanks for noticing this bug. It has been fixed in the latest version of the package with commit https://github.com/diogo-fernan/academicons/commit/97b833bd73da8569fb374c78a396541a7492306e.

Regards,
Diogo
