### ISSUE TITLE
Invalid operation fp_to_decimal(inf) l.12 \newfontfamily{\AI}{academicons.ttf}

### ISSUE THREAD

**Issue by JeffreyRacine** [diogo-fernan/academicons#9]
Greetings Diogo,

A file that was compiling happily stopped doing so on Sept 12 and I just noticed this (script auto generates)... the message is

! Undefined control sequence.
<argument> \LaTeX3 error:
                Invalid operation fp_to_decimal(inf)
l.12 \newfontfamily{\AI}{academicons.ttf}

If you had any suggestions that would be most welcome... the log states

.................................................
. fontspec info: "no-scripts"
. 
. Font "academicons" does not contain any OpenType `Script' information.
.................................................

! Undefined control sequence.
<argument> \LaTeX3 error: 
                Invalid operation fp_to_decimal(inf)
l.12 \newfontfamily{\AI}{academicons.ttf}
                                       
? 

I recall you issuing a fix for this issue so perhaps a change in another package is the culprit?

Regardless, thanks for your efforts and contributions to the community!

Jeff

**Comment by JeffreyRacine** [comment]
Apologies Diogo, I modded a system and installed texlive from macports that has the old version of academicians... removed and reinstalled mactex texlive and all is well. Thanks!

**Comment by diogo-fernan** [comment]
No worries. Thanks @JeffreyRacine :)
